### ISSUE TITLE
Page edit links are broken

### ISSUE THREAD

**Issue by dkbg** [tasks/docs#13]
The URLs for the "Edit this page" links at the bottom of every page all begin with "https://github.com/facebook/docusaurus" instead of pointing to this repo. I'm guessing this is the config line which needs to be changed: https://github.com/tasks/docs/blob/ba4fe2e51d9e292dcd8b53636979caf8ee9a7513/docusaurus.config.js#L104

**Comment by abaker** [comment]
Thanks! Fixed in 222cb6966bbedb4f8e6fbd55f10e141f7fb00a3e
