### ISSUE TITLE
Document sync conditions

### ISSUE THREAD

**Issue by RayBB** [tasks/docs#48]
I use your Android app along with nextcloud's tasks app and Mac OS reminders app.

For quite a while I'd have the occasional weirdness of them not seeming to be in sync the way I expected.
Tasks I added somewhere not showing up in the other places and whatnot. But it wasn't consistent enough for me to nail down.
However, I mostly use the android app and just pop into the others on occasion.

I asked in the tasks IRC what the sync conditions are and @abaker said:
> It syncs every hour in the background, or one minute after any local edits
> If you make consecutive changes it will sync one minute after the latest edit

I think this is very helpful information and would be good to document at https://tasks.org/docs/sync

I can open a PR for this if you want :)

Curious if there's any particular reason you don't make the app sync by default when you open it? Or at least if it hasn't been opened in the past X minutes?
I think that this would be the expected behavior based on my experience with most offline friendly apps (Pocket, Reminders, Ticktick, Obsidian, etc)

**Comment by abaker** [comment]
Yeah it probably should sync on open too
